# Generated by Django 5.2.7 on 2026-10-05 20:26

import apps.usuarios.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('giro', models.CharField(blank=True, help_text='A qué se dedica la organización.', max_length=150)),
                ('nombre_contacto', models.CharField(max_length=150)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('rut', models.CharField(help_text='Sin puntos ni guiones, o con ellos: se normaliza al guardar.', max_length=12, unique=True, validators=[apps.usuarios.models.ValidadorRut()], verbose_name='RUT')),
                ('modo', models.CharField(choices=[('registrada', 'Registrada'), ('invitada', 'Invitada')], default='registrada', help_text="'invitada' = creada por una reserva sin cuenta (D7).", max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Presentación breve.')),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[apps.usuarios.models.ValidadorRut()], verbose_name='RUT')),
                ('linkedin_url', models.URLField(blank=True, help_text='Se valida el formato de la URL, no el perfil real (decisión 3).', max_length=255)),
                ('estado', models.CharField(choices=[('postulando', 'Postulando'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido')], db_index=True, default='postulando', max_length=20)),
                ('disponibilidad', models.CharField(choices=[('inmediata', 'Inmediata'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='inmediata', max_length=20)),
                ('fecha_estado', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profesional',
                'verbose_name_plural': 'profesionales',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuarios.profesional')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'ordering': ['profesional', 'dia_semana', 'hora_inicio'],
            },
        ),
    ]
