# Generated by Django 5.2.7 on 2026-10-05 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_organizacion_profesional_horario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('devuelta', 'Devuelta')], db_index=True, default='pendiente', max_length=20)),
                ('comentarios_admin', models.TextField(blank=True, help_text='Se muestra al profesional al devolver o rechazar.')),
                ('experiencia', models.TextField(blank=True)),
                ('especialidad', models.CharField(blank=True, max_length=150)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='usuarios.profesional')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'postulación',
                'verbose_name_plural': 'postulaciones',
                'ordering': ['-fecha_postulacion'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('linkedin', 'LinkedIn'), ('otro', 'Otro documento')], default='otro', max_length=20)),
                ('nombre', models.CharField(help_text='Ej: Título profesional.', max_length=150)),
                ('archivo', models.FileField(blank=True, max_length=5242880, upload_to='certificados/%Y/%m/')),
                ('enlace', models.URLField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('verificado_automatico', 'Verificado automáticamente'), ('sin_reviewer', 'Sin revisar'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, max_length=30)),
                ('comentario_revisor', models.TextField(blank=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_revisados', to=settings.AUTH_USER_MODEL)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='postulaciones.postulacion')),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'ordering': ['-cargado_en'],
            },
        ),
    ]
