# Generated by Django 5.2.7 on 2026-10-07 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0002_organizacion_profesional_horario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=280)),
                ('descripcion_larga', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio fijo del servicio (CLP).', max_digits=10)),
                ('formato', models.CharField(choices=[('remoto', 'Remoto'), ('presencial', 'Presencial'), ('semipresencial', 'Semipresencial (Híbrido)')], max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('duracion_estimada', models.CharField(blank=True, help_text="Ej.: '2 horas', '3-5 días'.", max_length=100)),
                ('palabras_clave', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('devuelto', 'Devuelto'), ('suspendido', 'Suspendido')], db_index=True, default='borrador', max_length=20)),
                ('comentarios_admin', models.TextField(blank=True, help_text='Comentarios del administrador al devolver o rechazar.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='catalogo.categoria')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='usuarios.profesional')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='catalogo.servicio')),
            ],
            options={
                'verbose_name': 'entregable',
                'verbose_name_plural': 'entregables',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
